/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.App;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.TrackingsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trackings extends TableImpl<TrackingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app.trackings</code>
     */
    public static final Trackings TRACKINGS = new Trackings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrackingsRecord> getRecordType() {
        return TrackingsRecord.class;
    }

    /**
     * The column <code>app.trackings.tg_chat_id</code>.
     */
    public final TableField<TrackingsRecord, Long> TG_CHAT_ID = createField(DSL.name("tg_chat_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>app.trackings.link_id</code>.
     */
    public final TableField<TrackingsRecord, Long> LINK_ID = createField(DSL.name("link_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private Trackings(Name alias, Table<TrackingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Trackings(Name alias, Table<TrackingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>app.trackings</code> table reference
     */
    public Trackings(String alias) {
        this(DSL.name(alias), TRACKINGS);
    }

    /**
     * Create an aliased <code>app.trackings</code> table reference
     */
    public Trackings(Name alias) {
        this(alias, TRACKINGS);
    }

    /**
     * Create a <code>app.trackings</code> table reference
     */
    public Trackings() {
        this(DSL.name("trackings"), null);
    }

    public <O extends Record> Trackings(Table<O> child, ForeignKey<O, TrackingsRecord> key) {
        super(child, key, TRACKINGS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : App.APP;
    }

    @Override
    public UniqueKey<TrackingsRecord> getPrimaryKey() {
        return Keys.TRACKINGS_PK;
    }

    @Override
    public List<ForeignKey<TrackingsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRACKINGS__CHAT_FK, Keys.TRACKINGS__LINK_FK);
    }

    private transient Chats _chats;
    private transient Links _links;

    /**
     * Get the implicit join path to the <code>app.chats</code> table.
     */
    public Chats chats() {
        if (_chats == null)
            _chats = new Chats(this, Keys.TRACKINGS__CHAT_FK);

        return _chats;
    }

    /**
     * Get the implicit join path to the <code>app.links</code> table.
     */
    public Links links() {
        if (_links == null)
            _links = new Links(this, Keys.TRACKINGS__LINK_FK);

        return _links;
    }

    @Override
    public Trackings as(String alias) {
        return new Trackings(DSL.name(alias), this);
    }

    @Override
    public Trackings as(Name alias) {
        return new Trackings(alias, this);
    }

    @Override
    public Trackings as(Table<?> alias) {
        return new Trackings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Trackings rename(String name) {
        return new Trackings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Trackings rename(Name name) {
        return new Trackings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Trackings rename(Table<?> name) {
        return new Trackings(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
