/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chats;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Links;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Trackings;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app</code>
     */
    public static final App APP = new App();

    /**
     * The table <code>app.chats</code>.
     */
    public final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>app.links</code>.
     */
    public final Links LINKS = Links.LINKS;

    /**
     * The table <code>app.trackings</code>.
     */
    public final Trackings TRACKINGS = Trackings.TRACKINGS;

    /**
     * No further instances allowed
     */
    private App() {
        super("app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chats.CHATS,
            Links.LINKS,
            Trackings.TRACKINGS
        );
    }
}
