/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq;


import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chats;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Links;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Trackings;


/**
 * Convenience access to all tables in app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>app.chats</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>app.links</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>app.trackings</code>.
     */
    public static final Trackings TRACKINGS = Trackings.TRACKINGS;
}
